chicago/config/routes.rb
Rails.application.routes.draw do

  root 'places#index'

  # get '/places' => 'places#index'
  # get '/places/new' => 'places#new'
  # post '/places' => 'places#create'
  # get '/places/:id' => 'places#show'
  # delete '/places/:id' => 'places#destroy'
  # patch '/places/:id' => 'places#update'
  # get '/places/:id/edit' => 'places#edit'
  # post '/reviews/:places_id' => 'reviews#create'

  resources :places do
  	resources :reviews
  end
  
end

chicago/app/models/place.rb
class Place < ActiveRecord::Base
end

chicago/app/models/review.rb
class Review < ActiveRecord::Base
end

chicago/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

chicago/app/controllers/places_controller.rb
class PlacesController < ApplicationController

  def index
    @places = Place.all
  end

  def show
    @place = Place.find(params[:id])
  end

  def new
  end

  def create
    Place.create title: params[:title],
                 price: (params[:price].to_f * 100).to_i,
                 photo_url: params[:url],
                 desc: params[:desc]

    redirect_to root_path
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    @place = Place.find(params[:id])
    @place.update title: params[:title],
                 price: (params[:price].to_f * 100).to_i,
                 photo_url: params[:url],
                 desc: params[:desc]

    redirect_to place_path(params[:id])
  end

  def destroy
    Place.delete(params[:id])
    redirect_to root_path
  end


end

chicago/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    r = Review.new
    r.place_id = params["place_id"]
    r.rating = params["rating"]
    r.desc = params["desc"]
    r.save
    #redirect_to "/places/#{r.place_id}"
    redirect_to place_path(r.place_id)
  end

end

chicago/app/helpers/application_helper.rb
module ApplicationHelper
end

chicago/app/helpers/places_helper.rb
module PlacesHelper
end

chicago/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chicago</title>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <style>
    h1 {
      border-bottom: solid 3px gray;
      margin-bottom: 24px;
    }
  </style>

</head>
<body>

  <div class="container">

    <h1><%= link_to "Chicago", "/" %></h1>

    <% if notice.present? %>
      <div class="alert alert-info"%>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>

  </div>

</body>
</html>

chicago/app/views/places/edit.html.erb
<style>
  label { width: 100px; vertical-align: middle;}
</style>

<h2>Edit a Place</h2>

<!-- <form action="/places/<%= @place.id %>/submit_edit"> -->
<%= form_tag place_path(@place.id), :method => 'patch' do%>
  <p><label>Title:</label> <input value="<%= @place.title %>" name="title" size="30"></p>
  <p><label>Photo URL:</label> <input value="<%= @place.photo_url %>" name="url" size="80"></p>
  <p><label>Price:</label> <input name="price" value="<%= @place.price / 100.0 %>"></p>
  <p><label>Description:</label></p>
  <textarea name="desc" cols="80" rows="3"><%= @place.desc %></textarea>
  <p><button>Submit</button></p>
<!-- </form> -->
<%end%>

chicago/app/views/places/index.html.erb
<style>
  h1 {
    border-bottom: solid 3px gray;
    margin-bottom: 24px;
  }
</style>

<!-- <p><%= link_to "Add a New Place", "/places/new" %></p> -->
<p><%= link_to "Add a New Place", new_place_path, :method => 'get' %> </p>
<ul>

  <% @places.each do |place| %>
    <li>
      <%= link_to place.title, place_path(place.id) %>
      (<%= number_to_currency(place.price / 100) %>)
      <%= link_to "(delete)", place_path(place.id), :method => 'delete' %>
    </li>
  <% end %>

</ul>

chicago/app/views/places/new.html.erb
<style>
  label { width: 100px; vertical-align: middle;}
</style>

<h2>Add a New Place</h2>

<!-- <form action="/places/submit_new"> -->
<%= form_tag places_path, :method => 'post' do %>
  <p><label>Title:</label> <input name="title" size="30"></p>
  <p><label>Photo URL:</label> <input name="url" size="80"></p>
  <p><label>Price:</label> <input name="price"></p>
  <p><label>Description:</label></p>
  <textarea name="desc" cols="80" rows="3"></textarea>
  <p><button>Submit</button></p>
<!-- </form> -->
<% end %>

chicago/app/views/places/show.html.erb
<style>
  h2 {
    color: white;
    background: #006;
    padding: 6px;
    text-align: center;
  }
  .price {
    color: green;
    border: solid 3px green;
    padding: 4px;
  }
  img {
    float: left;
    margin-right: 40px;
    box-shadow: 8px 8px 4px gray;
    height: "200px";
  }
  p {
    margin-top: 24px;
    margin-bottom: 24px;
  }
</style>

<h2><%= @place.title %></h2>

<p>
  <span class="price">Admission Price: <%= number_to_currency @place.price/100 %></span>
  <%= link_to "Edit", edit_place_path(@place.id), :method => 'get' %>
</p>

<div>
<%= image_tag @place.photo_url, size: '200x200' %>

<p><%= @place.desc %></p>

<h3 style="clear:both; margin-top: 100px">Reviews</h3>

<p>Write a review</p>
<%= form_tag place_reviews_path(@place.id), :method => 'post' do %>
  <select name="rating">
    <option>5 star</option>
    <option>4 star</option>
    <option>3 star</option>
    <option>2 star</option>
    <option>1 star</option>
  </select>
  <input name="desc" size="50">
  <button>Submit</button>
<% end %>

<% Review.where(place_id: @place.id).order('id desc').each do |review| %>
  <p>
    <strong><%= ("&#9733;" * review.rating).html_safe  %></strong>
    <%= review.desc %>

  </p>
<% end %>

<p></p>